function Hd = wall_filter
%WALL_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 01-Dec-2025 19:19:25

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 6006;  % Sampling Frequency

Fstop = 600;         % Stopband Frequency
Fpass = 1000;         % Passband Frequency
Astop = 20;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
